name: General CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get-buck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: buck
          key: buck-${{ runner.os }}

      - name: Fetch buck
        run: |
          (mkdir buck && \
          wget https://jitpack.io/com/github/facebook/buck/v2021.01.12.01/buck-v2021.01.12.01-java11.pex && \
          mv buck-v2021.01.12.01-java11.pex buck/buck && \
          chmod +x buck/buck && \
          ls -l buck)

  tests:
    needs: [get-buck]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: buck
          key: buck-${{ runner.os }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run all library tests
        run: BUCK_PATH=`realpath buck/buck` ./gradlew test -x :litho-intellij-plugin:test --stacktrace

  deploy-check:
    name: Skip deploy if PR or Fork or not a SNAPSHOT version
    needs: [tests]
    if: ${{ github.event_name != 'pull_request' && github.repository == 'facebook/litho' }}
    runs-on: ubuntu-latest

    outputs:
      is-snapshot: ${{ steps.check_snapshot.outputs.IS_SNAPSHOT != '' }}

    steps:
      - uses: actions/checkout@v2

      - name: Check if SNAPSHOT version
        id: check_snapshot
        run: |
          echo ::set-output name=IS_SNAPSHOT::`grep 'VERSION_NAME=[0-9\.]\+-SNAPSHOT' gradle.properties)`

  deploy:
    needs: [deploy-check]
    if: ${{ needs.deploy-check.outputs.is-snapshot == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: buck
          key: buck-${{ runner.os }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Publish Snapshots
        run: BUCK_PATH=`realpath buck/buck` ./gradlew uploadArchives --stacktrace
